# Generated by bincast â https://github.com/benelser/bincast
# Homebrew formula for durable-runtime
class DurableRuntime < Formula
  desc "The SQLite of durable agent execution â crash-recoverable AI agents with exactly-once semantics. Zero dependencies."
  homepage "https://github.com/benelser/durable"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/durable/releases/download/v#{version}/durable-runtime-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/durable/releases/download/v#{version}/durable-runtime-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/durable/releases/download/v#{version}/durable-runtime-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/durable/releases/download/v#{version}/durable-runtime-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "durable"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/durable --version")
  end
end
